name: C/C++ CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        configure_args:
          - >-
            --enable-html-matrix=no
            --enable-parallel=no
            --enable-pytest=no
            --enable-shared=yes
            --enable-static=yes
            --enable-usrp=no
            --enable-winradio=no
            --with-cxx-binding=yes
            --with-indi=no
            --with-libusb=no
            --with-lua-binding=yes
            --with-perl-binding=no
            --with-python-binding=yes
            --with-readline=no
            --with-tcl-binding=no
            --with-xml-support=no

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew install autoconf
        brew install automake
        brew install libtool
        brew install grep
        brew install swig
        brew install lua
    - name: bootstrap
      run: ./bootstrap
    - name: Suppress -Winitializer-overrides on macOS
      if: runner.os == 'macOS'
      run: |
        export CFLAGS="$CFLAGS -Wno-initializer-overrides"
        export CXXFLAGS="$CXXFLAGS -Wno-initializer-overrides"
    - name: configure on macOS
      if: runner.os == 'macOS'
      run: ./configure ${{ matrix.configure_args }} --enable-silent-rules --without-python-binding LUA_INCLUDE=-I/opt/homebrew/Cellar/lua/5.4.8/include/lua/ LUA_LIB=/opt/homebrew/Cellar/lua/5.4.8/lib/
    - name: make distcheck
      run: make distcheck V=0 --no-print-directory
