name: C/C++ CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew install lua
        echo "python3-config --includes $(python3-config --includes)"
        echo "python3-config --ldflags $(python3-config --ldflags)"
        echo "HOMEBREW_PREFIX is set to $HOMEBREW_PREFIX"
        echo "brew --prefix $(brew --prefix)"
        find $(brew --prefix)  /usr/include/ /usr/local/include -name Python.h -o -name lua.h
